import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
// import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Homepage from "@/src/components/home/home-page";
import Footer from "@/src/components/footer/Footer";
import Header from "@/src/components/header/Header";

const inter = Inter({ subsets: ["latin"] });

function Home({ data }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  
     
      <Homepage  data={data}/>
    
     
    </>
  );
}

export default Home;

export async function getServerSideProps() {
  const { events_categories } = await import("../data/data.json");
  // console.log(events_categories );import Footer from './../src/components/footer/Footer';


  return {
    props: {
      data: events_categories,
    },
  };
}
